// react-frontend/src/layout/app/AppLayout.jsx
import { Layout, theme } from "antd";
import AppFooter from "./components/AppFooter";
import AppHeader from "./components/AppHeader";
import AppSider from "./components/AppSider";

const { Content } = Layout;

const AppLayout = ({ children }) => {
  const {
    token: { colorBgContainer, borderRadiusLG },
  } = theme.useToken();
  return (
    <Layout style={{ minHeight: "100vh" }}>
      <AppSider />
      <Layout>
        <AppHeader />
        <Content style={{ margin: "16px" }}>
          <div
            style={{
              padding: 24,
              minHeight: 360,
              background: colorBgContainer,
              borderRadius: borderRadiusLG,
            }}
          >
            {children}
          </div>
        </Content>
        <AppFooter />
      </Layout>
    </Layout>
  );
};
export default AppLayout;

// frontend/src/layouts/AppLayout.vue
<template>
    <a-layout class="layout">
        <AppHeader></AppHeader>
      <a-layout-content style="padding: 0 50px">
        <router-view />
      </a-layout-content>
      <AppFooter></AppFooter>
    </a-layout>
  </template>
  <script setup>
  import AppHeader from '@/components/Header/AppHeader.vue';
  import AppFooter from '@/components/Footer/AppFooter.vue';
  </script>
